### ISSUE TITLE
Return statement

### ISSUE THREAD

**Issue by ankolesn** [EdikGres/LabWorks-C-CPP#1]
https://github.com/EdikGres/LabWorks-C-CPP/blob/bd6eb34d55b69f78ae665df17ce888ab079a763b/Lab-work-2/Lab-work-2/Functions.cpp#L16-L24

it should be like this:
```cpp
return (ch >= 'A' && ch <= 'Z') || (ch >= 'a' && ch <= 'z')
```

**Comment by EdikGres** [comment]
Ok, thanks lil broudy, i fix it
